seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True

  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: True
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    std_output: exp
    network:
      - name: net
        input: STATES
        layers: [256, 128, 64]
        activations: elu
    output: ACTIONS
  
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [256, 128, 64]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# PPO agent configuration (field names are from PPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/ppo.html
agent:
  class: TRPO
  rollouts: 16
  learning_epochs: 8
  mini_batches: 2

  discount_factor: 0.99
  lambda: 0.95
  
  value_learning_rate: 0.001
  learning_rate_scheduler: None
  learning_rate_scheduler_kwargs: null

  state_preprocessor: None
  state_preprocessor_kwargs: null
  value_preprocessor: None
  value_preprocessor_kwargs: null

  random_timesteps: 0
  learning_starts: 0

  grad_norm_clip: 0.5
  value_loss_scale: 1.0

  damping: 0.1
  max_kl_divergence: 0.01
  conjugate_gradient_steps: 10
  max_backtrack_steps: 10
  accept_ratio: 0.5
  step_fraction: 1.0

  rewards_shaper: None
  time_limit_bootstrap: False

  # logging and checkpoint
  experiment:
    directory: "ur5e_lift_trpo"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 100000
  environment_info: log
